/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
    export interface GlobalComponents {
        Mdi: typeof import('./src/components/mdi.vue')['default'];
        NButton: typeof import('naive-ui')['NButton'];
        NConfigProvider: typeof import('naive-ui')['NConfigProvider'];
        NFlex: typeof import('naive-ui')['NFlex'];
        NGi: typeof import('naive-ui')['NGi'];
        NGrid: typeof import('naive-ui')['NGrid'];
        NImage: typeof import('naive-ui')['NImage'];
        NInput: typeof import('naive-ui')['NInput'];
        NLayout: typeof import('naive-ui')['NLayout'];
        NLayoutContent: typeof import('naive-ui')['NLayoutContent'];
        NLayoutHeader: typeof import('naive-ui')['NLayoutHeader'];
        NList: typeof import('naive-ui')['NList'];
        NListItem: typeof import('naive-ui')['NListItem'];
        NPagination: typeof import('naive-ui')['NPagination'];
        NSkeleton: typeof import('naive-ui')['NSkeleton'];
        NSpace: typeof import('naive-ui')['NSpace'];
        NTag: typeof import('naive-ui')['NTag'];
        NText: typeof import('naive-ui')['NText'];
        NThing: typeof import('naive-ui')['NThing'];
        NTooltip: typeof import('naive-ui')['NTooltip'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
    }
}
